export const metadata = {
  title: "OPC Training",
  description: "Generated by Shivendra Singh",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        {children}
      </body>
    </html>
  );
}
