import 'bootstrap/dist/css/bootstrap.min.css'
export const metadata = {
  title: 'OPC Training',
  description: 'Generated by Shivendra Singh'
}

export default function RootLayout ({ children }) {
  const menu = [
    { title: 'Home', path: '/' },
    { title: 'About', path: '/about' },
    { title: 'Contact', path: '/contact-us' },
    { title: 'Login', path: '/login' },
    { title: 'Signup', path: '/signup' }
  ]
  return (
    <html lang='en'>
      <body>
        <nav className='navbar navbar-expand-lg navbar-dark bg-dark sticky-top p-3'>
        <h1 className='text-white'>OPC</h1>
          <div className='container d-flex flex-wrap justify-content-between align-items-center'>
            {menu.map((item, index) => (
              <a key={index} href={item.path} className='nav-link text-white'>
                {item.title}
              </a>
            ))}
          </div>
        </nav>
        <section>{children}</section>
        <footer className='fixed-bottom text-center bg-dark text-white py-2'>
          OPC@2025
        </footer>
      </body>
    </html>
  )
}
