import Home from "./components/Home";
export const metadata = {
  title: "OPC Training",
  description: "Generated by Shivendra Singh",
};

const HomePage = () => {
  return <Home/>;
}

export default HomePage;
